
package Views;

import controllers.ConfigControllers;
import controllers.UsuariosController;
import controllers.ClientesController;
import models.Clientes;
import models.ClientesDAO;
import models.Usuarios;
import models.UsuariosDAO;

public class PanelAdmin extends javax.swing.JFrame {
    Usuarios us = new Usuarios();
    UsuariosDAO usDao = new UsuariosDAO();
    Clientes cl = new Clientes();
    ClientesDAO clDao = new ClientesDAO();
    
    public PanelAdmin() {
        initComponents();
        ConfigControllers config = new ConfigControllers(this);
        UsuariosController users = new UsuariosController(us, usDao, this);
        ClientesController cliente = new ClientesController(cl, clDao, this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupUsuarios = new javax.swing.JPopupMenu();
        jMenuEliminarUser = new javax.swing.JMenuItem();
        jMenuReingresarUser = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        JPanelNuevaVenta = new javax.swing.JPanel();
        JLabelNuevaVenta = new javax.swing.JLabel();
        JPanelNuevaCompra = new javax.swing.JPanel();
        JLabelNuevaCompra = new javax.swing.JLabel();
        JPanelProductos = new javax.swing.JPanel();
        JLabelProductos = new javax.swing.JLabel();
        JPanelClientes = new javax.swing.JPanel();
        JLabelClientes = new javax.swing.JLabel();
        JPanelProveedor = new javax.swing.JPanel();
        JLabelProveedores = new javax.swing.JLabel();
        JPanelMedidas = new javax.swing.JPanel();
        JLabelMedidas = new javax.swing.JLabel();
        JPanelCategorias = new javax.swing.JPanel();
        JLabelCategorias = new javax.swing.JLabel();
        JPanelConfiguracion = new javax.swing.JPanel();
        JLabelConfiguracion = new javax.swing.JLabel();
        JPanelUsuarios = new javax.swing.JPanel();
        JLabelUsuarios = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtBuscarProducto = new javax.swing.JTextField();
        btnUsers = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtCodigoProducto = new javax.swing.JTextField();
        txtDescripcionProducto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtPrecioCompraProducto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecioVentaProducto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbProveedorProducto = new javax.swing.JComboBox<>();
        cbMedidaProducto = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cbCategoriaProducto = new javax.swing.JComboBox<>();
        btnNuevoProducto = new javax.swing.JButton();
        btnModificarProducto = new javax.swing.JButton();
        btnRegistrarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableProductos = new javax.swing.JTable();
        PaginadorProducto = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        btnNuevoCliente = new javax.swing.JButton();
        btnRegistrarCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtTelefonoCliente = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDireccionCliente = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableClientes = new javax.swing.JTable();
        PaginadorCliente = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        btnNuevoProveedor = new javax.swing.JButton();
        btnRegistrarProveedor = new javax.swing.JButton();
        btnModificarProveedor = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtNombreProveedor = new javax.swing.JTextField();
        txtTelefonoProveedor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtDireccionProveedor = new javax.swing.JTextPane();
        jLabel15 = new javax.swing.JLabel();
        txtRucProveedor = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableProveedor = new javax.swing.JTable();
        PaginadorProveedor = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        PaginadorUser = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        btnNuevoUser = new javax.swing.JButton();
        btnRegistrarUser = new javax.swing.JButton();
        btnModificarUser = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtNombreUser = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtUsuarioUser = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cbCajaUser = new javax.swing.JComboBox<>();
        cbRolUser = new javax.swing.JComboBox<>();
        txtClaveUser = new javax.swing.JPasswordField();
        txtIdUser = new javax.swing.JTextField();
        jScrollPane7 = new javax.swing.JScrollPane();
        TableUser = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        btnNuevoCategoria = new javax.swing.JButton();
        btnRegistrarCategoria = new javax.swing.JButton();
        btnModificarCategoria = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        txtNombreCategoria = new javax.swing.JTextField();
        jScrollPane8 = new javax.swing.JScrollPane();
        TableCategoria = new javax.swing.JTable();
        PaginadorCategoria = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        btnNuevoMedida = new javax.swing.JButton();
        btnRegistrarMedida = new javax.swing.JButton();
        btnModificarMedida = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        txtNombreMedida = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        txtNombreCortoMedida = new javax.swing.JTextField();
        jScrollPane9 = new javax.swing.JScrollPane();
        TableMedida = new javax.swing.JTable();
        PaginadorMedida = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TableNV = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtCodigoNV = new javax.swing.JTextField();
        txtProductoNV = new javax.swing.JTextField();
        txtTotalNV = new javax.swing.JTextField();
        txtStockNV = new javax.swing.JTextField();
        txtPrecioNV = new javax.swing.JTextField();
        txtCantidadNV = new javax.swing.JTextField();
        btnGenerarNV = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        JLabelTotalPagar = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane11 = new javax.swing.JScrollPane();
        TableVentas = new javax.swing.JTable();
        PaginadorVentas = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        TableCompras = new javax.swing.JTable();
        PaginadorCompras = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        btnModificarEmpresa = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        txtNombreEmpresa = new javax.swing.JTextField();
        txtTelefonoEmpresa = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtDireccionEmpresa = new javax.swing.JTextPane();
        jLabel46 = new javax.swing.JLabel();
        txtRucEmpresa = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtMensajeEmpresa = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        TableNC = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        txtCodigoNC = new javax.swing.JTextField();
        txtProductoNC = new javax.swing.JTextField();
        txtTotalNC = new javax.swing.JTextField();
        txtPrecioNC = new javax.swing.JTextField();
        txtCantidadNC = new javax.swing.JTextField();
        btnGenerarNC = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        JLabelTotalPagar1 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();

        jMenuEliminarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/eliminar.png"))); // NOI18N
        jMenuEliminarUser.setText("Eliminar");
        jPopupUsuarios.add(jMenuEliminarUser);

        jMenuReingresarUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/exchange.png"))); // NOI18N
        jMenuReingresarUser.setText("Reingresar");
        jPopupUsuarios.add(jMenuReingresarUser);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 44, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JPanelNuevaVenta.setBackground(new java.awt.Color(44, 44, 44));

        JLabelNuevaVenta.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        JLabelNuevaVenta.setForeground(new java.awt.Color(255, 255, 255));
        JLabelNuevaVenta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelNuevaVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Nventa.png"))); // NOI18N
        JLabelNuevaVenta.setText("Nueva Venta");
        JLabelNuevaVenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelNuevaVentaLayout = new javax.swing.GroupLayout(JPanelNuevaVenta);
        JPanelNuevaVenta.setLayout(JPanelNuevaVentaLayout);
        JPanelNuevaVentaLayout.setHorizontalGroup(
            JPanelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelNuevaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelNuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPanelNuevaVentaLayout.setVerticalGroup(
            JPanelNuevaVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelNuevaVentaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelNuevaVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(JPanelNuevaVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 180, 40));

        JPanelNuevaCompra.setBackground(new java.awt.Color(44, 44, 44));

        JLabelNuevaCompra.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        JLabelNuevaCompra.setForeground(new java.awt.Color(255, 255, 255));
        JLabelNuevaCompra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelNuevaCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Carrito-de-compras.png"))); // NOI18N
        JLabelNuevaCompra.setText("Nueva Compra");
        JLabelNuevaCompra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelNuevaCompraLayout = new javax.swing.GroupLayout(JPanelNuevaCompra);
        JPanelNuevaCompra.setLayout(JPanelNuevaCompraLayout);
        JPanelNuevaCompraLayout.setHorizontalGroup(
            JPanelNuevaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelNuevaCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelNuevaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPanelNuevaCompraLayout.setVerticalGroup(
            JPanelNuevaCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelNuevaCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelNuevaCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(JPanelNuevaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 180, 40));

        JPanelProductos.setBackground(new java.awt.Color(44, 44, 44));

        JLabelProductos.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        JLabelProductos.setForeground(new java.awt.Color(255, 255, 255));
        JLabelProductos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/producto.png"))); // NOI18N
        JLabelProductos.setText("Productos");
        JLabelProductos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelProductosLayout = new javax.swing.GroupLayout(JPanelProductos);
        JPanelProductos.setLayout(JPanelProductosLayout);
        JPanelProductosLayout.setHorizontalGroup(
            JPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPanelProductosLayout.setVerticalGroup(
            JPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelProductosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(JPanelProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 180, 40));

        JPanelClientes.setBackground(new java.awt.Color(44, 44, 44));

        JLabelClientes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        JLabelClientes.setForeground(new java.awt.Color(255, 255, 255));
        JLabelClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Clientes.png"))); // NOI18N
        JLabelClientes.setText("Clientes");
        JLabelClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelClientesLayout = new javax.swing.GroupLayout(JPanelClientes);
        JPanelClientes.setLayout(JPanelClientesLayout);
        JPanelClientesLayout.setHorizontalGroup(
            JPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPanelClientesLayout.setVerticalGroup(
            JPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelClientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(JPanelClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 180, 40));

        JPanelProveedor.setBackground(new java.awt.Color(44, 44, 44));

        JLabelProveedores.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        JLabelProveedores.setForeground(new java.awt.Color(255, 255, 255));
        JLabelProveedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelProveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/proveedor.png"))); // NOI18N
        JLabelProveedores.setText("Proveedores");
        JLabelProveedores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelProveedorLayout = new javax.swing.GroupLayout(JPanelProveedor);
        JPanelProveedor.setLayout(JPanelProveedorLayout);
        JPanelProveedorLayout.setHorizontalGroup(
            JPanelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelProveedorLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(JLabelProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        JPanelProveedorLayout.setVerticalGroup(
            JPanelProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelProveedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(JPanelProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 180, 40));

        JPanelMedidas.setBackground(new java.awt.Color(44, 44, 44));

        JLabelMedidas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        JLabelMedidas.setForeground(new java.awt.Color(255, 255, 255));
        JLabelMedidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelMedidas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/medidas.png"))); // NOI18N
        JLabelMedidas.setText("Medidas");
        JLabelMedidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelMedidasLayout = new javax.swing.GroupLayout(JPanelMedidas);
        JPanelMedidas.setLayout(JPanelMedidasLayout);
        JPanelMedidasLayout.setHorizontalGroup(
            JPanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMedidasLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(JLabelMedidas, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        JPanelMedidasLayout.setVerticalGroup(
            JPanelMedidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelMedidasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelMedidas, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(JPanelMedidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 180, 40));

        JPanelCategorias.setBackground(new java.awt.Color(44, 44, 44));

        JLabelCategorias.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        JLabelCategorias.setForeground(new java.awt.Color(255, 255, 255));
        JLabelCategorias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelCategorias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/categoria.png"))); // NOI18N
        JLabelCategorias.setText("Categorías");
        JLabelCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelCategoriasLayout = new javax.swing.GroupLayout(JPanelCategorias);
        JPanelCategorias.setLayout(JPanelCategoriasLayout);
        JPanelCategoriasLayout.setHorizontalGroup(
            JPanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelCategoriasLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(JLabelCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        JPanelCategoriasLayout.setVerticalGroup(
            JPanelCategoriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelCategoriasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelCategorias, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(JPanelCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 180, 40));

        JPanelConfiguracion.setBackground(new java.awt.Color(44, 44, 44));

        JLabelConfiguracion.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        JLabelConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        JLabelConfiguracion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelConfiguracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/config.png"))); // NOI18N
        JLabelConfiguracion.setText("Configuración");
        JLabelConfiguracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelConfiguracionLayout = new javax.swing.GroupLayout(JPanelConfiguracion);
        JPanelConfiguracion.setLayout(JPanelConfiguracionLayout);
        JPanelConfiguracionLayout.setHorizontalGroup(
            JPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConfiguracionLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(JLabelConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );
        JPanelConfiguracionLayout.setVerticalGroup(
            JPanelConfiguracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelConfiguracionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelConfiguracion, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(JPanelConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, 180, 40));

        JPanelUsuarios.setBackground(new java.awt.Color(44, 44, 44));

        JLabelUsuarios.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        JLabelUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        JLabelUsuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/users.png"))); // NOI18N
        JLabelUsuarios.setText("Usuarios");
        JLabelUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout JPanelUsuariosLayout = new javax.swing.GroupLayout(JPanelUsuarios);
        JPanelUsuarios.setLayout(JPanelUsuariosLayout);
        JPanelUsuariosLayout.setHorizontalGroup(
            JPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPanelUsuariosLayout.setVerticalGroup(
            JPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelUsuariosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(JPanelUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 180, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 200, 580));

        jPanel2.setBackground(new java.awt.Color(195, 60, 68));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel49.setForeground(new java.awt.Color(255, 255, 255));
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo.png"))); // NOI18N
        jPanel2.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 100));

        jPanel3.setBackground(new java.awt.Color(172, 60, 60));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscarProducto.setBackground(new java.awt.Color(44, 44, 44));
        txtBuscarProducto.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(txtBuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(624, 34, 240, 35));

        btnUsers.setBackground(new java.awt.Color(44, 44, 44));
        btnUsers.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnUsers.setForeground(new java.awt.Color(255, 255, 255));
        btnUsers.setText("Users");
        jPanel3.add(btnUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 30, 120, 40));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/consulta.png"))); // NOI18N
        jPanel3.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, -1, 60));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1100, 100));

        jTabbedPane1.setBackground(new java.awt.Color(44, 44, 44));
        jTabbedPane1.setForeground(java.awt.Color.white);

        jPanel4.setBackground(new java.awt.Color(140, 132, 152));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel15.setBackground(new java.awt.Color(44, 44, 44));
        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Nuevo Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Código");
        jPanel15.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 40, 125, 35));
        jPanel15.add(txtCodigoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 41, 125, 35));
        jPanel15.add(txtDescripcionProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 95, 125, 35));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Descripción");
        jPanel15.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 94, 125, 35));
        jPanel15.add(txtPrecioCompraProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 149, 125, 35));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Precio Compra");
        jPanel15.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 148, 125, 35));
        jPanel15.add(txtPrecioVentaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 203, 125, 35));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Precio Venta");
        jPanel15.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 202, 125, 35));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Proveedor");
        jPanel15.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 256, 125, 35));

        jPanel15.add(cbProveedorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 257, 125, 35));

        jPanel15.add(cbMedidaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 310, 125, 35));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("Medida");
        jPanel15.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 309, 125, 35));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("Categoría");
        jPanel15.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 359, 125, 35));

        jPanel15.add(cbCategoriaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 360, 125, 35));

        btnNuevoProducto.setBackground(new java.awt.Color(44, 44, 44));
        btnNuevoProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProducto.setText("Nuevo");
        jPanel15.add(btnNuevoProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, 40));

        btnModificarProducto.setBackground(new java.awt.Color(44, 44, 44));
        btnModificarProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnModificarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarProducto.setText("Modificar");
        jPanel15.add(btnModificarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 120, 40));

        btnRegistrarProducto.setBackground(new java.awt.Color(44, 44, 44));
        btnRegistrarProducto.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRegistrarProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarProducto.setText("Registrar");
        jPanel15.add(btnRegistrarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 120, 40));

        jPanel4.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 510));

        TableProductos.setBackground(new java.awt.Color(44, 44, 44));
        TableProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Precio", "Cantidad", "Medida", "Estado"
            }
        ));
        TableProductos.setSelectionForeground(new java.awt.Color(44, 44, 44));
        jScrollPane1.setViewportView(TableProductos);
        if (TableProductos.getColumnModel().getColumnCount() > 0) {
            TableProductos.getColumnModel().getColumn(1).setHeaderValue("Usuario");
            TableProductos.getColumnModel().getColumn(3).setHeaderValue("Rol");
            TableProductos.getColumnModel().getColumn(4).setHeaderValue("Medida");
        }

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 770, -1));

        PaginadorProducto.setBackground(new java.awt.Color(44, 44, 44));

        javax.swing.GroupLayout PaginadorProductoLayout = new javax.swing.GroupLayout(PaginadorProducto);
        PaginadorProducto.setLayout(PaginadorProductoLayout);
        PaginadorProductoLayout.setHorizontalGroup(
            PaginadorProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        PaginadorProductoLayout.setVerticalGroup(
            PaginadorProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel4.add(PaginadorProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 770, 50));

        jTabbedPane1.addTab("tab1", jPanel4);

        jPanel5.setBackground(new java.awt.Color(140, 132, 152));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(44, 44, 44));
        jPanel17.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Nuevo Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoCliente.setBackground(new java.awt.Color(44, 44, 44));
        btnNuevoCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCliente.setText("Nuevo");
        jPanel17.add(btnNuevoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, 40));

        btnRegistrarCliente.setBackground(new java.awt.Color(44, 44, 44));
        btnRegistrarCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRegistrarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarCliente.setText("Registrar");
        jPanel17.add(btnRegistrarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 120, 40));

        btnModificarCliente.setBackground(new java.awt.Color(44, 44, 44));
        btnModificarCliente.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnModificarCliente.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarCliente.setText("Modificar");
        jPanel17.add(btnModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 120, 40));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Nombre");
        jPanel17.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 40, 125, 35));
        jPanel17.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 41, 125, 35));
        jPanel17.add(txtTelefonoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 95, 125, 35));

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Teléfono");
        jPanel17.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 94, 125, 35));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Dirección");
        jPanel17.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 148, 125, 35));

        jScrollPane3.setViewportView(txtDireccionCliente);

        jPanel17.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 148, 125, 115));

        jPanel5.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 510));

        TableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Teléfono", "Dirección", "Estado"
            }
        ));
        jScrollPane2.setViewportView(TableClientes);

        jPanel5.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 770, -1));

        PaginadorCliente.setBackground(new java.awt.Color(44, 44, 44));

        javax.swing.GroupLayout PaginadorClienteLayout = new javax.swing.GroupLayout(PaginadorCliente);
        PaginadorCliente.setLayout(PaginadorClienteLayout);
        PaginadorClienteLayout.setHorizontalGroup(
            PaginadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        PaginadorClienteLayout.setVerticalGroup(
            PaginadorClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel5.add(PaginadorCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 770, 50));

        jTabbedPane1.addTab("tab2", jPanel5);

        jPanel6.setBackground(new java.awt.Color(140, 132, 152));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel18.setBackground(new java.awt.Color(44, 44, 44));
        jPanel18.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Nuevo Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoProveedor.setBackground(new java.awt.Color(44, 44, 44));
        btnNuevoProveedor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNuevoProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoProveedor.setText("Nuevo");
        jPanel18.add(btnNuevoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, 40));

        btnRegistrarProveedor.setBackground(new java.awt.Color(44, 44, 44));
        btnRegistrarProveedor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRegistrarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarProveedor.setText("Registrar");
        jPanel18.add(btnRegistrarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 120, 40));

        btnModificarProveedor.setBackground(new java.awt.Color(44, 44, 44));
        btnModificarProveedor.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnModificarProveedor.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarProveedor.setText("Modificar");
        jPanel18.add(btnModificarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 120, 40));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Nombre");
        jPanel18.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 91, 125, 35));
        jPanel18.add(txtNombreProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 92, 125, 35));
        jPanel18.add(txtTelefonoProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 146, 125, 35));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Teléfono");
        jPanel18.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 145, 125, 35));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Dirección");
        jPanel18.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 199, 125, 35));

        jScrollPane4.setViewportView(txtDireccionProveedor);

        jPanel18.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 199, 125, 115));

        jLabel15.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("RUC");
        jPanel18.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 37, 125, 35));
        jPanel18.add(txtRucProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 38, 125, 35));

        jPanel6.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 510));

        TableProveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Teléfono", "Dirección", "Estado"
            }
        ));
        jScrollPane5.setViewportView(TableProveedor);
        if (TableProveedor.getColumnModel().getColumnCount() > 0) {
            TableProveedor.getColumnModel().getColumn(1).setHeaderValue("Usuario");
            TableProveedor.getColumnModel().getColumn(3).setHeaderValue("Rol");
        }

        jPanel6.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 770, -1));

        PaginadorProveedor.setBackground(new java.awt.Color(44, 44, 44));

        javax.swing.GroupLayout PaginadorProveedorLayout = new javax.swing.GroupLayout(PaginadorProveedor);
        PaginadorProveedor.setLayout(PaginadorProveedorLayout);
        PaginadorProveedorLayout.setHorizontalGroup(
            PaginadorProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        PaginadorProveedorLayout.setVerticalGroup(
            PaginadorProveedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel6.add(PaginadorProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 770, 50));

        jTabbedPane1.addTab("tab3", jPanel6);

        jPanel7.setBackground(new java.awt.Color(140, 132, 152));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PaginadorUser.setBackground(new java.awt.Color(44, 44, 44));

        javax.swing.GroupLayout PaginadorUserLayout = new javax.swing.GroupLayout(PaginadorUser);
        PaginadorUser.setLayout(PaginadorUserLayout);
        PaginadorUserLayout.setHorizontalGroup(
            PaginadorUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        PaginadorUserLayout.setVerticalGroup(
            PaginadorUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel7.add(PaginadorUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 770, 50));

        jPanel19.setBackground(new java.awt.Color(44, 44, 44));
        jPanel19.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Nuevo Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoUser.setBackground(new java.awt.Color(44, 44, 44));
        btnNuevoUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNuevoUser.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoUser.setText("Nuevo");
        jPanel19.add(btnNuevoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, 40));

        btnRegistrarUser.setBackground(new java.awt.Color(44, 44, 44));
        btnRegistrarUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRegistrarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarUser.setText("Registrar");
        jPanel19.add(btnRegistrarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 120, 40));

        btnModificarUser.setBackground(new java.awt.Color(44, 44, 44));
        btnModificarUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnModificarUser.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarUser.setText("Modificar");
        jPanel19.add(btnModificarUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 120, 40));

        jLabel16.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nombre");
        jPanel19.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 91, 125, 35));

        txtNombreUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel19.add(txtNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 92, 125, 35));

        jLabel17.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Contraseña");
        jPanel19.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 145, 125, 35));

        jLabel18.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Caja");
        jPanel19.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 198, 125, 35));

        jLabel19.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Usuario");
        jPanel19.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 37, 125, 35));

        txtUsuarioUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel19.add(txtUsuarioUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 38, 125, 35));

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Rol");
        jPanel19.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 252, 125, 35));

        cbCajaUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cbCajaUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "General" }));
        jPanel19.add(cbCajaUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 199, 125, 35));

        cbRolUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        cbRolUser.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Administrador" }));
        jPanel19.add(cbRolUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 253, 125, 35));

        txtClaveUser.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jPanel19.add(txtClaveUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 145, 125, 35));
        jPanel19.add(txtIdUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 50, 40));

        jPanel7.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 510));

        TableUser.setBackground(new java.awt.Color(44, 44, 44));
        TableUser.setForeground(new java.awt.Color(255, 255, 255));
        TableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Nombre", "Rol", "Caja", "Estado"
            }
        ));
        TableUser.setComponentPopupMenu(jPopupUsuarios);
        jScrollPane7.setViewportView(TableUser);
        if (TableUser.getColumnModel().getColumnCount() > 0) {
            TableUser.getColumnModel().getColumn(1).setHeaderValue("Usuario");
            TableUser.getColumnModel().getColumn(3).setHeaderValue("Rol");
            TableUser.getColumnModel().getColumn(4).setHeaderValue("Caja");
        }

        jPanel7.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 770, -1));

        jTabbedPane1.addTab("tab4", jPanel7);

        jPanel8.setBackground(new java.awt.Color(140, 132, 152));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(44, 44, 44));
        jPanel20.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Nueva Categoría", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoCategoria.setBackground(new java.awt.Color(44, 44, 44));
        btnNuevoCategoria.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNuevoCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoCategoria.setText("Nuevo");
        jPanel20.add(btnNuevoCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, 40));

        btnRegistrarCategoria.setBackground(new java.awt.Color(44, 44, 44));
        btnRegistrarCategoria.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRegistrarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarCategoria.setText("Registrar");
        jPanel20.add(btnRegistrarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 120, 40));

        btnModificarCategoria.setBackground(new java.awt.Color(44, 44, 44));
        btnModificarCategoria.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnModificarCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarCategoria.setText("Modificar");
        jPanel20.add(btnModificarCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 120, 40));

        jLabel24.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Nombre");
        jPanel20.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 37, 125, 35));
        jPanel20.add(txtNombreCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 38, 125, 35));

        jPanel8.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 510));

        TableCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Estado"
            }
        ));
        jScrollPane8.setViewportView(TableCategoria);

        jPanel8.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 770, -1));

        PaginadorCategoria.setBackground(new java.awt.Color(44, 44, 44));

        javax.swing.GroupLayout PaginadorCategoriaLayout = new javax.swing.GroupLayout(PaginadorCategoria);
        PaginadorCategoria.setLayout(PaginadorCategoriaLayout);
        PaginadorCategoriaLayout.setHorizontalGroup(
            PaginadorCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        PaginadorCategoriaLayout.setVerticalGroup(
            PaginadorCategoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel8.add(PaginadorCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 770, 50));

        jTabbedPane1.addTab("tab5", jPanel8);

        jPanel9.setBackground(new java.awt.Color(140, 132, 152));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel21.setBackground(new java.awt.Color(44, 44, 44));
        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Nueva Medida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNuevoMedida.setBackground(new java.awt.Color(44, 44, 44));
        btnNuevoMedida.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnNuevoMedida.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoMedida.setText("Nuevo");
        jPanel21.add(btnNuevoMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 120, 40));

        btnRegistrarMedida.setBackground(new java.awt.Color(44, 44, 44));
        btnRegistrarMedida.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnRegistrarMedida.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarMedida.setText("Registrar");
        jPanel21.add(btnRegistrarMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 120, 40));

        btnModificarMedida.setBackground(new java.awt.Color(44, 44, 44));
        btnModificarMedida.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnModificarMedida.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarMedida.setText("Modificar");
        jPanel21.add(btnModificarMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 120, 40));

        jLabel25.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Nombre");
        jPanel21.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 37, 125, 35));
        jPanel21.add(txtNombreMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 38, 125, 35));

        jLabel26.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Nombre Corto");
        jPanel21.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 91, 125, 35));
        jPanel21.add(txtNombreCortoMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 92, 125, 35));

        jPanel9.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 510));

        TableMedida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Nombre Corto", "Estado"
            }
        ));
        jScrollPane9.setViewportView(TableMedida);

        jPanel9.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 770, -1));

        PaginadorMedida.setBackground(new java.awt.Color(44, 44, 44));

        javax.swing.GroupLayout PaginadorMedidaLayout = new javax.swing.GroupLayout(PaginadorMedida);
        PaginadorMedida.setLayout(PaginadorMedidaLayout);
        PaginadorMedidaLayout.setHorizontalGroup(
            PaginadorMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
        );
        PaginadorMedidaLayout.setVerticalGroup(
            PaginadorMedidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel9.add(PaginadorMedida, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 770, 50));

        jTabbedPane1.addTab("tab6", jPanel9);

        jPanel10.setBackground(new java.awt.Color(140, 132, 152));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripción", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane6.setViewportView(TableNV);

        jPanel10.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1080, 350));

        jLabel21.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(44, 44, 44));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("Código");
        jPanel10.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, -1));

        jLabel22.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(44, 44, 44));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("Total");
        jPanel10.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 70, -1));

        txtCodigoNV.setBackground(new java.awt.Color(44, 44, 44));
        txtCodigoNV.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(txtCodigoNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 130, -1));

        txtProductoNV.setBackground(new java.awt.Color(44, 44, 44));
        txtProductoNV.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(txtProductoNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 200, -1));

        txtTotalNV.setBackground(new java.awt.Color(44, 44, 44));
        txtTotalNV.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(txtTotalNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 70, -1));

        txtStockNV.setBackground(new java.awt.Color(44, 44, 44));
        txtStockNV.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(txtStockNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 50, 50, -1));

        txtPrecioNV.setBackground(new java.awt.Color(44, 44, 44));
        txtPrecioNV.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(txtPrecioNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 70, -1));

        txtCantidadNV.setBackground(new java.awt.Color(44, 44, 44));
        txtCantidadNV.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(txtCantidadNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 50, -1));

        btnGenerarNV.setBackground(new java.awt.Color(44, 44, 44));
        btnGenerarNV.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnGenerarNV.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarNV.setText("Generar");
        jPanel10.add(btnGenerarNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, -1, -1));

        jLabel23.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(44, 44, 44));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Producto");
        jPanel10.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 200, -1));

        jLabel27.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(44, 44, 44));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("Stock");
        jPanel10.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(833, 20, 50, -1));

        jLabel28.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(44, 44, 44));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Precio");
        jPanel10.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 70, -1));

        jLabel29.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(44, 44, 44));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel29.setText("Cant");
        jPanel10.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 50, -1));

        jLabel30.setBackground(new java.awt.Color(44, 44, 44));
        jLabel30.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(44, 44, 44));
        jLabel30.setText("Cliente");
        jPanel10.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 60, 30));

        jComboBox1.setBackground(new java.awt.Color(44, 44, 44));
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 260, 30));

        jTextField1.setBackground(new java.awt.Color(44, 44, 44));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 90, 30));

        jTextField2.setBackground(new java.awt.Color(44, 44, 44));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel10.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 90, 30));

        jLabel31.setBackground(new java.awt.Color(44, 44, 44));
        jLabel31.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(44, 44, 44));
        jLabel31.setText("Total a Pagar");
        jPanel10.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, -1, 30));

        JLabelTotalPagar.setBackground(new java.awt.Color(44, 44, 44));
        JLabelTotalPagar.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        JLabelTotalPagar.setForeground(new java.awt.Color(44, 44, 44));
        JLabelTotalPagar.setText("-----------");
        jPanel10.add(JLabelTotalPagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 470, -1, 30));

        jLabel32.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(44, 44, 44));
        jLabel32.setText("Cambio");
        jPanel10.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, -1, 30));

        jLabel33.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(44, 44, 44));
        jLabel33.setText("Paga con");
        jPanel10.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, 30));

        jTabbedPane1.addTab("tab7", jPanel10);

        jPanel11.setBackground(new java.awt.Color(140, 132, 152));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Cliente", "Total", "Fecha"
            }
        ));
        jScrollPane11.setViewportView(TableVentas);

        jPanel11.add(jScrollPane11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1060, -1));

        PaginadorVentas.setBackground(new java.awt.Color(44, 44, 44));

        javax.swing.GroupLayout PaginadorVentasLayout = new javax.swing.GroupLayout(PaginadorVentas);
        PaginadorVentas.setLayout(PaginadorVentasLayout);
        PaginadorVentasLayout.setHorizontalGroup(
            PaginadorVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        PaginadorVentasLayout.setVerticalGroup(
            PaginadorVentasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel11.add(PaginadorVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 1060, 50));

        jTabbedPane1.addTab("tab8", jPanel11);

        jPanel12.setBackground(new java.awt.Color(140, 132, 152));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Proveedor", "Total", "Fecha"
            }
        ));
        jScrollPane12.setViewportView(TableCompras);

        jPanel12.add(jScrollPane12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 1060, -1));

        PaginadorCompras.setBackground(new java.awt.Color(44, 44, 44));

        javax.swing.GroupLayout PaginadorComprasLayout = new javax.swing.GroupLayout(PaginadorCompras);
        PaginadorCompras.setLayout(PaginadorComprasLayout);
        PaginadorComprasLayout.setHorizontalGroup(
            PaginadorComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1060, Short.MAX_VALUE)
        );
        PaginadorComprasLayout.setVerticalGroup(
            PaginadorComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel12.add(PaginadorCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 1060, 50));

        jTabbedPane1.addTab("tab9", jPanel12);

        jPanel13.setBackground(new java.awt.Color(140, 132, 152));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel22.setBackground(new java.awt.Color(44, 44, 44));
        jPanel22.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "Datos de la Empresa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("SansSerif", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificarEmpresa.setBackground(new java.awt.Color(44, 44, 44));
        btnModificarEmpresa.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnModificarEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarEmpresa.setText("Modificar");
        jPanel22.add(btnModificarEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 411, 258, 40));

        jLabel37.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Nombre");
        jPanel22.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 91, 125, 35));
        jPanel22.add(txtNombreEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 92, 125, 35));
        jPanel22.add(txtTelefonoEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 146, 125, 35));

        jLabel44.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(255, 255, 255));
        jLabel44.setText("Teléfono");
        jPanel22.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 145, 125, 35));

        jLabel45.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setText("Dirección");
        jPanel22.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 199, 125, 35));

        jScrollPane13.setViewportView(txtDireccionEmpresa);

        jPanel22.add(jScrollPane13, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 199, 125, 76));

        jLabel46.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel46.setForeground(new java.awt.Color(255, 255, 255));
        jLabel46.setText("RUC");
        jPanel22.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 37, 125, 35));
        jPanel22.add(txtRucEmpresa, new org.netbeans.lib.awtextra.AbsoluteConstraints(144, 38, 125, 35));

        jLabel47.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(255, 255, 255));
        jLabel47.setText("Mensaje");
        jPanel22.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 293, 125, 35));

        jScrollPane14.setViewportView(txtMensajeEmpresa);

        jPanel22.add(jScrollPane14, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 293, 127, 62));

        jPanel13.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 280, 470));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo.png"))); // NOI18N
        jPanel13.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 330, 240));

        jTabbedPane1.addTab("tab10", jPanel13);

        jPanel14.setBackground(new java.awt.Color(140, 132, 152));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1098, Short.MAX_VALUE)
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab11", jPanel14);

        jPanel16.setBackground(new java.awt.Color(140, 132, 152));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableNC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Descripción", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane10.setViewportView(TableNC);

        jPanel16.add(jScrollPane10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1080, 350));

        jLabel34.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(44, 44, 44));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel34.setText("Código");
        jPanel16.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 130, -1));

        jLabel35.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(44, 44, 44));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Total");
        jPanel16.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 20, 70, -1));

        txtCodigoNC.setBackground(new java.awt.Color(44, 44, 44));
        txtCodigoNC.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(txtCodigoNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 130, -1));

        txtProductoNC.setBackground(new java.awt.Color(44, 44, 44));
        txtProductoNC.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(txtProductoNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 50, 200, -1));

        txtTotalNC.setBackground(new java.awt.Color(44, 44, 44));
        txtTotalNC.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(txtTotalNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 70, -1));

        txtPrecioNC.setBackground(new java.awt.Color(44, 44, 44));
        txtPrecioNC.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(txtPrecioNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 70, -1));

        txtCantidadNC.setBackground(new java.awt.Color(44, 44, 44));
        txtCantidadNC.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(txtCantidadNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 50, -1));

        btnGenerarNC.setBackground(new java.awt.Color(44, 44, 44));
        btnGenerarNC.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        btnGenerarNC.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarNC.setText("Generar");
        jPanel16.add(btnGenerarNC, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 40, -1, -1));

        jLabel36.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(44, 44, 44));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Producto");
        jPanel16.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 200, -1));

        jLabel38.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(44, 44, 44));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel38.setText("Precio");
        jPanel16.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 70, -1));

        jLabel39.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(44, 44, 44));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel39.setText("Cant");
        jPanel16.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 50, -1));

        jLabel40.setBackground(new java.awt.Color(44, 44, 44));
        jLabel40.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(44, 44, 44));
        jLabel40.setText("Proveedor");
        jPanel16.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 80, 30));

        jComboBox2.setBackground(new java.awt.Color(44, 44, 44));
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, 260, 30));

        jTextField3.setBackground(new java.awt.Color(44, 44, 44));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 470, 90, 30));

        jTextField4.setBackground(new java.awt.Color(44, 44, 44));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jPanel16.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 470, 90, 30));

        jLabel41.setBackground(new java.awt.Color(44, 44, 44));
        jLabel41.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(44, 44, 44));
        jLabel41.setText("Total a Pagar");
        jPanel16.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 470, -1, 30));

        JLabelTotalPagar1.setBackground(new java.awt.Color(44, 44, 44));
        JLabelTotalPagar1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        JLabelTotalPagar1.setForeground(new java.awt.Color(44, 44, 44));
        JLabelTotalPagar1.setText("-----------");
        jPanel16.add(JLabelTotalPagar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 470, -1, 30));

        jLabel42.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(44, 44, 44));
        jLabel42.setText("Cambio");
        jPanel16.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 470, -1, 30));

        jLabel43.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel43.setForeground(new java.awt.Color(44, 44, 44));
        jLabel43.setText("Paga con");
        jPanel16.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, -1, 30));

        jTabbedPane1.addTab("Nueva Compra", jPanel16);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 1100, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JLabelCategorias;
    public javax.swing.JLabel JLabelClientes;
    public javax.swing.JLabel JLabelConfiguracion;
    public javax.swing.JLabel JLabelMedidas;
    public javax.swing.JLabel JLabelNuevaCompra;
    public javax.swing.JLabel JLabelNuevaVenta;
    public javax.swing.JLabel JLabelProductos;
    public javax.swing.JLabel JLabelProveedores;
    private javax.swing.JLabel JLabelTotalPagar;
    private javax.swing.JLabel JLabelTotalPagar1;
    public javax.swing.JLabel JLabelUsuarios;
    public javax.swing.JPanel JPanelCategorias;
    public javax.swing.JPanel JPanelClientes;
    public javax.swing.JPanel JPanelConfiguracion;
    public javax.swing.JPanel JPanelMedidas;
    public javax.swing.JPanel JPanelNuevaCompra;
    public javax.swing.JPanel JPanelNuevaVenta;
    public javax.swing.JPanel JPanelProductos;
    public javax.swing.JPanel JPanelProveedor;
    public javax.swing.JPanel JPanelUsuarios;
    private javax.swing.JPanel PaginadorCategoria;
    public javax.swing.JPanel PaginadorCliente;
    private javax.swing.JPanel PaginadorCompras;
    private javax.swing.JPanel PaginadorMedida;
    private javax.swing.JPanel PaginadorProducto;
    private javax.swing.JPanel PaginadorProveedor;
    private javax.swing.JPanel PaginadorUser;
    private javax.swing.JPanel PaginadorVentas;
    private javax.swing.JTable TableCategoria;
    public javax.swing.JTable TableClientes;
    private javax.swing.JTable TableCompras;
    private javax.swing.JTable TableMedida;
    private javax.swing.JTable TableNC;
    private javax.swing.JTable TableNV;
    private javax.swing.JTable TableProductos;
    private javax.swing.JTable TableProveedor;
    public javax.swing.JTable TableUser;
    private javax.swing.JTable TableVentas;
    private javax.swing.JButton btnGenerarNC;
    private javax.swing.JButton btnGenerarNV;
    private javax.swing.JButton btnModificarCategoria;
    public javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnModificarEmpresa;
    private javax.swing.JButton btnModificarMedida;
    private javax.swing.JButton btnModificarProducto;
    private javax.swing.JButton btnModificarProveedor;
    public javax.swing.JButton btnModificarUser;
    private javax.swing.JButton btnNuevoCategoria;
    public javax.swing.JButton btnNuevoCliente;
    private javax.swing.JButton btnNuevoMedida;
    private javax.swing.JButton btnNuevoProducto;
    private javax.swing.JButton btnNuevoProveedor;
    public javax.swing.JButton btnNuevoUser;
    private javax.swing.JButton btnRegistrarCategoria;
    public javax.swing.JButton btnRegistrarCliente;
    private javax.swing.JButton btnRegistrarMedida;
    private javax.swing.JButton btnRegistrarProducto;
    private javax.swing.JButton btnRegistrarProveedor;
    public javax.swing.JButton btnRegistrarUser;
    private javax.swing.JButton btnUsers;
    public javax.swing.JComboBox<String> cbCajaUser;
    private javax.swing.JComboBox<String> cbCategoriaProducto;
    private javax.swing.JComboBox<String> cbMedidaProducto;
    private javax.swing.JComboBox<String> cbProveedorProducto;
    public javax.swing.JComboBox<String> cbRolUser;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JMenuItem jMenuEliminarUser;
    public javax.swing.JMenuItem jMenuReingresarUser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtCantidadNC;
    private javax.swing.JTextField txtCantidadNV;
    public javax.swing.JPasswordField txtClaveUser;
    private javax.swing.JTextField txtCodigoNC;
    private javax.swing.JTextField txtCodigoNV;
    private javax.swing.JTextField txtCodigoProducto;
    private javax.swing.JTextField txtDescripcionProducto;
    public javax.swing.JTextPane txtDireccionCliente;
    private javax.swing.JTextPane txtDireccionEmpresa;
    private javax.swing.JTextPane txtDireccionProveedor;
    public javax.swing.JTextField txtIdUser;
    private javax.swing.JTextPane txtMensajeEmpresa;
    private javax.swing.JTextField txtNombreCategoria;
    public javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtNombreCortoMedida;
    private javax.swing.JTextField txtNombreEmpresa;
    private javax.swing.JTextField txtNombreMedida;
    private javax.swing.JTextField txtNombreProveedor;
    public javax.swing.JTextField txtNombreUser;
    private javax.swing.JTextField txtPrecioCompraProducto;
    private javax.swing.JTextField txtPrecioNC;
    private javax.swing.JTextField txtPrecioNV;
    private javax.swing.JTextField txtPrecioVentaProducto;
    private javax.swing.JTextField txtProductoNC;
    private javax.swing.JTextField txtProductoNV;
    private javax.swing.JTextField txtRucEmpresa;
    private javax.swing.JTextField txtRucProveedor;
    private javax.swing.JTextField txtStockNV;
    public javax.swing.JTextField txtTelefonoCliente;
    private javax.swing.JTextField txtTelefonoEmpresa;
    private javax.swing.JTextField txtTelefonoProveedor;
    private javax.swing.JTextField txtTotalNC;
    private javax.swing.JTextField txtTotalNV;
    public javax.swing.JTextField txtUsuarioUser;
    // End of variables declaration//GEN-END:variables
}
